apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  namespace: default

spec:
  replicas: 3
  selector:
    matchLabels: # This also can match other pods with the same label that was not created by this ReplicaSet
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx:latest