apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  namespace: default
  labels:
    app: myapp

spec:
  replicas: 3
  # selector:
  #   app: myapp
  template:
    metadata:
      # name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx:latest