apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: busybox:latest
        command: ["sleep"]
        args: ["3600"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      # nodePort: 30007

# Jobs to print the IP in the logs
---
apiVersion: batch/v1
kind: Job
metadata:
  name: demo
  namespace: test
spec:
  template:
    spec:
      containers:
      - name: demo
        image: busybox:latest
        command: ["nslookup", "my-service"]
      restartPolicy: Never
  backoffLimit: 4
