apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutorial
  template:
    metadata:
      labels:
        app: tutorial
    spec:
      containers:
      - name: tutorial
        image: docker/getting-started
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tutorial
spec:
  selector:
    app: tutorial
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
